# Generated by Django 5.2rc1 on 2025-04-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blauth', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
