# Generated by Django 5.2rc1 on 2025-04-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.ImageField(upload_to='uploads/%Y/%m/%d', verbose_name='photo')),
            ],
            options={
                'verbose_name': '相册',
                'verbose_name_plural': '相册',
                'db_table': 'photo',
            },
        ),
    ]
