# Generated by Django 5.2rc1 on 2025-04-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_alter_userprofile_options_alter_userprofile_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='place',
            field=models.CharField(default='Chongqing', max_length=50),
        ),
    ]
